/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/AnimationHuman.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function First(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/AnimationHuman.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[-7.421, 3.265, -1.007]} rotation={[0.778, 1.448, -0.781]}>
          <primitive object={nodes.Bone} />
          <primitive object={nodes.Bone003} />
          <primitive object={nodes.Bone005} />
          <group name="LeftArm001">
            <skinnedMesh name="Mesh_1" geometry={nodes.Mesh_1.geometry} material={materials.Skin} skeleton={nodes.Mesh_1.skeleton} />
            <skinnedMesh name="Mesh_2" geometry={nodes.Mesh_2.geometry} material={materials.Hair} skeleton={nodes.Mesh_2.skeleton} />
            <skinnedMesh name="Mesh_3" geometry={nodes.Mesh_3.geometry} material={materials.Material} skeleton={nodes.Mesh_3.skeleton} />
          </group>
        </group>
        <group name="Cube001" position={[14.455, 5.918, 0.641]} scale={[0.104, 6.007, 23.358]} />
        <group name="Plane010" position={[-10.246, 8.295, -2.31]} rotation={[0, 0, -Math.PI / 2]} scale={[0.121, 2.68, 2.282]} />
        <group name="NurbsPath001" position={[-8.871, 5.814, -9.541]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[-0.088, -1, -1]} />
        <group name="Empty" position={[-9.423, 8.291, 19.657]} rotation={[1.579, 0.005, 3.138]} scale={[1, 1.47, 1]} />
        <mesh name="Plane007" geometry={nodes.Plane007.geometry} material={materials['Material.033']} position={[-6.358, 1.971, -0.548]} />
        <mesh name="Cube009" geometry={nodes.Cube009.geometry} material={materials['Material.026']} position={[-10.964, 1.077, 3.397]} scale={[1.099, 1, 0.517]} />
        <group name="Cube007" position={[-12.91, 4.079, 0.097]} rotation={[-2.727, -0.317, 0.136]} scale={[0.046, 0.006, 0.201]}>
          <mesh name="Cube007_1" geometry={nodes.Cube007_1.geometry} material={materials['Material.015']} />
          <mesh name="Cube007_2" geometry={nodes.Cube007_2.geometry} material={materials['Material.016']} />
        </group>
        <group name="Cube006" position={[-11.315, 0, -0.185]} scale={[2.563, 0.146, 4.522]}>
          <mesh name="Cube006_1" geometry={nodes.Cube006_1.geometry} material={materials['Material.013']} />
          <mesh name="Cube006_2" geometry={nodes.Cube006_2.geometry} material={materials['Material.014']} />
          <mesh name="Cube006_3" geometry={nodes.Cube006_3.geometry} material={materials['Material.015']} />
        </group>
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Material.003']} position={[0.475, 0, 0.563]} rotation={[Math.PI, -1.565, Math.PI]} scale={[19.144, 0.078, 14.012]} />
        <mesh name="Circle002" geometry={nodes.Circle002.geometry} material={materials['Material.025']} position={[-6.276, 1.971, -0.548]} />
        <mesh name="Circle" geometry={nodes.Circle.geometry} material={materials['Material.010']} position={[-0.547, 15.377, -3.748]} />
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials['Material.007']} position={[-13.719, 4.131, 0.653]} rotation={[Math.PI, 0, -3.14]} scale={[0.182, 4.134, 19.126]} />
        <mesh name="Circle001" geometry={nodes.Circle001.geometry} material={materials['Material.019']} position={[-0.547, 10.734, 0.038]} rotation={[0.019, 0.491, -0.018]} />
        <group name="Circle003" position={[-0.547, 10.734, 0.038]} rotation={[0.016, 0, -0.009]}>
          <mesh name="Circle001_1" geometry={nodes.Circle001_1.geometry} material={materials['Material.019']} />
          <mesh name="Circle001_2" geometry={nodes.Circle001_2.geometry} material={materials['Material.028']} />
        </group>
        <mesh name="Plane075" geometry={nodes.Plane075.geometry} material={materials['Material.023']} position={[-13.015, 10.107, -0.646]} rotation={[0.205, -0.331, -1.489]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane074" geometry={nodes.Plane074.geometry} material={materials['Material.023']} position={[-12.399, 10.17, -0.219]} rotation={[0.205, -0.331, -1.489]} scale={[0.076, 0.104, 0.043]} />
        <mesh name="Plane073" geometry={nodes.Plane073.geometry} material={materials['Material.023']} position={[-12.41, 10.129, 0.154]} rotation={[0.205, -0.331, -1.489]} scale={[0.076, 0.104, 0.043]} />
        <mesh name="Plane072" geometry={nodes.Plane072.geometry} material={materials['Material.023']} position={[-12.927, 10.2, 0.464]} rotation={[0.205, -0.331, -1.489]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane071" geometry={nodes.Plane071.geometry} material={materials['Material.023']} position={[-12.936, 10.141, 0.282]} rotation={[0.205, -0.331, -1.489]} scale={[0.076, 0.104, 0.043]} />
        <mesh name="Plane070" geometry={nodes.Plane070.geometry} material={materials['Material.023']} position={[-12.99, 10.179, -0.046]} rotation={[0.205, -0.331, -1.489]} scale={[0.076, 0.104, 0.043]} />
        <mesh name="Plane069" geometry={nodes.Plane069.geometry} material={materials['Material.023']} position={[-12.918, 10.047, 0.071]} rotation={[0.205, -0.331, -1.489]} scale={[0.076, 0.104, 0.043]} />
        <mesh name="Plane068" geometry={nodes.Plane068.geometry} material={materials['Material.023']} position={[-12.898, 9.966, -0.074]} rotation={[0.205, -0.331, -1.489]} scale={[0.076, 0.104, 0.043]} />
        <mesh name="Plane067" geometry={nodes.Plane067.geometry} material={materials['Material.023']} position={[-13.046, 10.208, -0.43]} rotation={[0.205, -0.331, -1.489]} scale={[0.076, 0.104, 0.043]} />
        <mesh name="Plane066" geometry={nodes.Plane066.geometry} material={materials['Material.023']} position={[-12.941, 9.98, -0.397]} rotation={[0.205, -0.331, -1.489]} scale={[0.076, 0.104, 0.043]} />
        <mesh name="Plane065" geometry={nodes.Plane065.geometry} material={materials['Material.023']} position={[-12.98, 10.032, -0.541]} rotation={[0.205, -0.331, -1.489]} scale={[0.076, 0.104, 0.043]} />
        <mesh name="Plane064" geometry={nodes.Plane064.geometry} material={materials['Material.023']} position={[-12.977, 10.069, -0.365]} rotation={[0.205, -0.331, -1.489]} scale={[0.076, 0.104, 0.043]} />
        <mesh name="Plane063" geometry={nodes.Plane063.geometry} material={materials['Material.023']} position={[-13.011, 10.109, -0.507]} rotation={[0.205, -0.331, -1.489]} scale={[0.076, 0.104, 0.043]} />
        <mesh name="Plane062" geometry={nodes.Plane062.geometry} material={materials['Material.023']} position={[-13.08, 10.184, -0.1]} rotation={[0.205, -0.331, -1.489]} scale={[0.076, 0.104, 0.043]} />
        <mesh name="Plane061" geometry={nodes.Plane061.geometry} material={materials['Material.023']} position={[-13.092, 9.977, -0.24]} rotation={[0.205, -0.331, -1.489]} scale={[0.076, 0.104, 0.043]} />
        <mesh name="Plane060" geometry={nodes.Plane060.geometry} material={materials['Material.023']} position={[-12.669, 10.176, 0.082]} rotation={[0.205, -0.331, -1.489]} scale={[0.076, 0.104, 0.043]} />
        <mesh name="Plane059" geometry={nodes.Plane059.geometry} material={materials['Material.023']} position={[-12.663, 10.181, -0.179]} rotation={[0.205, -0.331, -1.489]} scale={[0.076, 0.104, 0.043]} />
        <mesh name="Plane058" geometry={nodes.Plane058.geometry} material={materials['Material.023']} position={[-12.74, 10.08, -0.22]} rotation={[0.205, -0.331, -1.489]} scale={[0.076, 0.104, 0.043]} />
        <mesh name="Plane057" geometry={nodes.Plane057.geometry} material={materials['Material.023']} position={[-13.012, 10.024, -0.268]} rotation={[0.205, -0.331, -1.489]} scale={[0.076, 0.104, 0.043]} />
        <mesh name="Plane056" geometry={nodes.Plane056.geometry} material={materials['Material.023']} position={[-12.894, 10.06, -0.244]} rotation={[0.205, -0.331, -1.489]} scale={[0.076, 0.104, 0.043]} />
        <mesh name="Plane055" geometry={nodes.Plane055.geometry} material={materials['Material.023']} position={[-12.922, 10.207, -0.2]} rotation={[0.205, -0.331, -1.489]} scale={[0.076, 0.104, 0.043]} />
        <mesh name="Plane054" geometry={nodes.Plane054.geometry} material={materials['Material.023']} position={[-12.833, 10.071, -0.236]} rotation={[0.205, -0.331, -1.489]} scale={[0.076, 0.104, 0.043]} />
        <mesh name="Plane053" geometry={nodes.Plane053.geometry} material={materials['Material.023']} position={[-12.944, 10.071, -0.307]} rotation={[0.205, -0.331, -1.489]} scale={[0.076, 0.104, 0.043]} />
        <mesh name="Plane052" geometry={nodes.Plane052.geometry} material={materials['Material.023']} position={[-12.759, 10.121, -0.154]} rotation={[0.205, -0.331, -1.489]} scale={[0.076, 0.104, 0.043]} />
        <mesh name="Plane051" geometry={nodes.Plane051.geometry} material={materials['Material.023']} position={[-12.992, 10.135, -0.294]} rotation={[0.205, -0.331, -1.489]} scale={[0.076, 0.104, 0.043]} />
        <mesh name="Plane050" geometry={nodes.Plane050.geometry} material={materials['Material.023']} position={[-12.951, 10.112, 0.031]} rotation={[0.205, -0.331, -1.489]} scale={[0.076, 0.104, 0.043]} />
        <mesh name="Plane049" geometry={nodes.Plane049.geometry} material={materials['Material.023']} position={[-12.938, 10.117, 0.228]} rotation={[0.205, -0.331, -1.489]} scale={[0.076, 0.104, 0.043]} />
        <mesh name="Plane048" geometry={nodes.Plane048.geometry} material={materials['Material.023']} position={[-12.235, 9.832, 0.191]} rotation={[-0.509, -0.386, -0.87]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane047" geometry={nodes.Plane047.geometry} material={materials['Material.023']} position={[-12.876, 9.775, -0.645]} rotation={[-0.509, -0.386, -0.87]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane046" geometry={nodes.Plane046.geometry} material={materials['Material.023']} position={[-12.87, 9.649, -0.689]} rotation={[-0.509, -0.386, -0.87]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane045" geometry={nodes.Plane045.geometry} material={materials['Material.023']} position={[-12.609, 9.466, -0.723]} rotation={[-0.509, -0.386, -0.87]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane044" geometry={nodes.Plane044.geometry} material={materials['Material.023']} position={[-12.84, 9.517, -0.72]} rotation={[-0.509, -0.386, -0.87]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane043" geometry={nodes.Plane043.geometry} material={materials['Material.023']} position={[-12.233, 9.891, -0.204]} rotation={[-0.509, -0.386, -0.87]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane042" geometry={nodes.Plane042.geometry} material={materials['Material.023']} position={[-12.11, 9.767, -0.267]} rotation={[-0.509, -0.386, -0.87]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane041" geometry={nodes.Plane041.geometry} material={materials['Material.023']} position={[-12.11, 9.695, -0.491]} rotation={[-0.509, -0.386, -0.87]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane040" geometry={nodes.Plane040.geometry} material={materials['Material.023']} position={[-11.965, 9.483, 0.198]} rotation={[-0.509, -0.386, -0.87]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane039" geometry={nodes.Plane039.geometry} material={materials['Material.023']} position={[-11.917, 9.374, 0.214]} rotation={[-0.509, -0.386, -0.87]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane038" geometry={nodes.Plane038.geometry} material={materials['Material.023']} position={[-11.886, 9.242, 0.252]} rotation={[-0.509, -0.386, -0.87]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane037" geometry={nodes.Plane037.geometry} material={materials['Material.023']} position={[-11.88, 9.056, 0.308]} rotation={[-0.509, -0.386, -0.87]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane036" geometry={nodes.Plane036.geometry} material={materials['Material.023']} position={[-11.674, 7.798, 0.116]} rotation={[0.806, 0.661, -1.113]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane035" geometry={nodes.Plane035.geometry} material={materials['Material.023']} position={[-11.941, 8.129, 0.215]} rotation={[2.764, 0.277, -2.314]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane034" geometry={nodes.Plane034.geometry} material={materials['Material.023']} position={[-12.802, 9.879, 0.647]} rotation={[-0.509, -0.386, -0.87]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane033" geometry={nodes.Plane033.geometry} material={materials['Material.023']} position={[-12.16, 9.69, 0.126]} rotation={[-0.509, -0.386, -0.87]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane032" geometry={nodes.Plane032.geometry} material={materials['Material.023']} position={[-12.769, 9.55, 0.795]} rotation={[-0.509, -0.386, -0.87]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane031" geometry={nodes.Plane031.geometry} material={materials['Material.023']} position={[-12.265, 8.965, 0.99]} rotation={[-0.509, -0.386, -0.87]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane030" geometry={nodes.Plane030.geometry} material={materials['Material.023']} position={[-12.249, 8.708, 1.012]} rotation={[-0.509, -0.386, -0.87]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane029" geometry={nodes.Plane029.geometry} material={materials['Material.023']} position={[-12.087, 7.856, 1.079]} rotation={[-0.509, -0.386, -0.87]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane028" geometry={nodes.Plane028.geometry} material={materials['Material.023']} position={[-12.253, 8.259, 0.907]} rotation={[0.746, 0.636, -1.077]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane027" geometry={nodes.Plane027.geometry} material={materials['Material.023']} position={[-12.07, 9.603, -0.539]} rotation={[-0.509, -0.386, -0.87]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane026" geometry={nodes.Plane026.geometry} material={materials['Material.023']} position={[-12.079, 9.446, -0.577]} rotation={[-0.728, -0.537, -0.968]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane025" geometry={nodes.Plane025.geometry} material={materials['Material.023']} position={[-12.093, 9.303, -0.635]} rotation={[-0.509, -0.386, -0.87]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane024" geometry={nodes.Plane024.geometry} material={materials['Material.023']} position={[-12.503, 9.243, -0.663]} rotation={[-0.509, -0.386, -0.87]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane023" geometry={nodes.Plane023.geometry} material={materials['Material.023']} position={[-12.409, 9.074, -0.743]} rotation={[-0.509, -0.386, -0.87]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane022" geometry={nodes.Plane022.geometry} material={materials['Material.023']} position={[-12.459, 8.827, -0.901]} rotation={[0.196, 0.274, -0.826]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane021" geometry={nodes.Plane021.geometry} material={materials['Material.023']} position={[-11.973, 8.571, -0.75]} rotation={[2.386, 0.552, -2.159]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane020" geometry={nodes.Plane020.geometry} material={materials['Material.023']} position={[-11.476, 7.545, -1.133]} rotation={[-1.772, -0.781, -1.65]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane019" geometry={nodes.Plane019.geometry} material={materials['Material.023']} position={[-11.788, 8.233, -0.627]} rotation={[-0.969, -0.655, -1.104]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane018" geometry={nodes.Plane018.geometry} material={materials['Material.023']} position={[-11.702, 8.01, -0.755]} rotation={[-0.628, -0.473, -0.92]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane017" geometry={nodes.Plane017.geometry} material={materials['Material.023']} position={[-11.593, 7.712, -1.042]} rotation={[-0.479, -0.362, -0.859]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane016" geometry={nodes.Plane016.geometry} material={materials['Material.023']} position={[-11.969, 8.899, -0.572]} rotation={[-1.994, -0.756, -1.805]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane015" geometry={nodes.Plane015.geometry} material={materials['Material.023']} position={[-11.878, 8.871, 0.342]} rotation={[-0.509, -0.386, -0.87]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane014" geometry={nodes.Plane014.geometry} material={materials['Material.023']} position={[-11.907, 8.494, 0.391]} rotation={[-0.509, -0.386, -0.87]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane013" geometry={nodes.Plane013.geometry} material={materials['Material.023']} position={[-11.827, 8.506, 0.256]} rotation={[2.472, -0.084, -2.058]} scale={[0.069, 0.095, 0.04]} />
        <mesh name="Plane011" geometry={nodes.Plane011.geometry} material={materials['Material.018']} position={[-14.127, 6.4, 10.39]} rotation={[0, 0, -Math.PI / 2]} scale={[0.121, 2.68, 2.282]} />
        <mesh name="Plane009" geometry={nodes.Plane009.geometry} material={materials['Material.002']} position={[-13.011, 9.675, -0.093]} rotation={[0, 0, -Math.PI / 2]} scale={[0.121, 2.68, 2.282]} />
        <mesh name="NurbsPath005" geometry={nodes.NurbsPath005.geometry} material={materials['Material.021']} position={[-13.645, 10.509, -0.489]} rotation={[0, -0.558, 0]} />
        <mesh name="NurbsPath004" geometry={nodes.NurbsPath004.geometry} material={materials['Material.021']} position={[-13.825, 10.378, -0.429]} rotation={[-0.067, 0.287, 0.113]} />
        <mesh name="NurbsPath003" geometry={nodes.NurbsPath003.geometry} material={materials['Material.021']} position={[-13.706, 10.518, -0.488]} />
        <mesh name="NurbsPath002" geometry={nodes.NurbsPath002.geometry} material={materials['Material.021']} position={[-13.773, 10.504, -0.219]} />
        <mesh name="Cube011" geometry={nodes.Cube011.geometry} material={materials['Material.017']} position={[-12.826, 3.919, 3.163]} rotation={[0, -1.519, -Math.PI]} scale={[-0.062, -0.419, -0.165]} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/AnimationHuman.glb')
